---
- name: practice ansible lint playbook
  hosts: all
  vars:
    - var1: val1
  pre_tasks:
    - name: Pre_task1
      ansible.builtin.facts:

  roles:
    - test_role
  task:
    - name: Task1
      ansible.builtin.debug:
        msg: "Task1 has run"

    - name: Task2
        ansible.builtin.debug:
          var: ansible_facts



















